@dpsBase = http://localhost:8000/api/v1
@authToken = user_token_123

### Iniciar post-proceso de fragmentos
POST {{dpsBase}}/post-process-fragment/start
Accept: application/json
Authorization: Bearer {{authToken}}


### Encolar por documentos
POST {{dpsBase}}/post-process-fragment/documents
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "document_ids": [1, 2]
}


### Estado
GET {{dpsBase}}/post-process-fragment/status
Accept: application/json
Authorization: Bearer {{authToken}}


### Detener
DELETE {{dpsBase}}/post-process-fragment/stop
Accept: application/json
Authorization: Bearer {{authToken}}
