INSERT INTO permission (name, description)
VALUES
       -- ============================================================
       -- aura-document-processing-service
       -- ============================================================
       ('DOCUMENT_CREATE', 'Crear un documento subiendo un archivo (carga e ingesta en el pipeline)'),
       ('DOCUMENT_QUERY', 'Consultar documentos del usuario: detalle, estado de procesamiento y listado por chat'),
       ('DOCUMENT_QUERY_MANAGE', 'Consultar cualquier documento sin restricción de pertenencia al chat (admin)'),
       ('DOCUMENT_DOWNLOAD', 'Descargar el archivo de un documento (usuario, verifica pertenencia al chat)'),
       ('DOCUMENT_DOWNLOAD_MANAGE', 'Descargar el archivo de cualquier documento sin restricción (admin)'),
       ('DOCUMENT_DELETE', 'Eliminar lógicamente (soft delete) documentos propios o de un chat'),
       ('DOCUMENT_DELETE_MANAGE',
        'Eliminar lógicamente cualquier documento sin restricción de pertenencia al chat (admin)'),
       ('DOCUMENT_RESTORE_MANAGE', 'Restaurar cualquier documento eliminado lógicamente (admin)'),
       ('DOCUMENT_UPDATE_MANAGE', 'Actualizar la metadata de cualquier documento (admin)'),
       ('DOCUMENT_SEARCH', 'Buscar documentos por similitud de contenido (vectorial)'),
       ('DOCUMENT_REEMBED_MANAGE', 'Re-embeber los fragmentos de uno, varios o todos los documentos (admin)'),
       ('DOCUMENT_REPROCESS_MANAGE',
        'Reprocesar (re-download, re-chunk, re-embed) uno, varios o todos los documentos (admin)'),
       ('DOCUMENT_ENRICH_MANAGE', 'Enriquecer por LLM los fragmentos de uno, varios o todos los documentos (admin)'),
       ('FRAGMENT_QUERY', 'Obtener fragmentos de contexto por pregunta o por documentos'),
       ('GRAPH_QUERY', 'Consultar el grafo de conocimiento (consulta en lenguaje natural y contexto RAG)'),
       ('GRAPH_ENTITY', 'Obtener una entidad del grafo y sus relaciones'),
       ('GRAPH_PATH', 'Buscar caminos entre entidades del grafo'),
       ('GRAPH_SEARCH', 'Buscar entidades del grafo por nombre (autocomplete)'),
       ('GRAPH_ONTOLOGY', 'Consultar la ontología activa del grafo de conocimiento'),
       ('GRAPH_STATS_MANAGE', 'Consultar estadísticas de cobertura del grafo de conocimiento (admin)'),
       ('GRAPH_EXTRACT_MANAGE', 'Extraer el grafo de conocimiento para uno, varios o todos los documentos (admin)'),

       -- ============================================================
       -- aura-document-collection-service
       -- ============================================================
       ('LIST_DOCUMENT_COLLECTIONS', 'Listar colecciones documentales MAC'),
       ('CREATE_DOCUMENT_COLLECTION', 'Crear colección documental'),
       ('GET_DOCUMENT_COLLECTION', 'Ver detalle de colección documental'),
       ('UPDATE_DOCUMENT_COLLECTION', 'Actualizar colección documental'),
       ('DELETE_DOCUMENT_COLLECTION', 'Eliminar colección documental'),
       ('LIST_DOCUMENT_COLLECTION_DOCUMENTS', 'Listar documentos enlazados a una colección'),
       ('ADD_DOCUMENT_COLLECTION_DOCUMENT', 'Añadir documento a una colección'),
       ('REMOVE_DOCUMENT_COLLECTION_DOCUMENT', 'Quitar documento de una colección'),
       ('LIST_CLASSIFICATION_LEVELS', 'Listar niveles de clasificación'),
       ('CREATE_CLASSIFICATION_LEVEL', 'Crear nivel de clasificación'),
       ('GET_CLASSIFICATION_LEVEL', 'Ver nivel de clasificación'),
       ('UPDATE_CLASSIFICATION_LEVEL', 'Actualizar nivel de clasificación'),
       ('DELETE_CLASSIFICATION_LEVEL', 'Eliminar nivel de clasificación'),
       ('LIST_COMPARTMENTS', 'Listar compartimentos'),
       ('CREATE_COMPARTMENT', 'Crear compartimento'),
       ('GET_COMPARTMENT', 'Ver compartimento'),
       ('UPDATE_COMPARTMENT', 'Actualizar compartimento'),
       ('DELETE_COMPARTMENT', 'Eliminar compartimento'),
       ('GET_USER_AUTHORIZATION', 'Ver autorización MAC de usuario'),
       ('SET_USER_CLEARANCE', 'Asignar nivel de clasificación del usuario'),
       ('DELETE_USER_CLEARANCE', 'Quitar nivel de clasificación del usuario'),
       ('LIST_USER_COMPARTMENTS', 'Listar compartimentos del usuario'),
       ('ADD_USER_COMPARTMENT', 'Asignar compartimento al usuario'),
       ('REMOVE_USER_COMPARTMENT', 'Quitar compartimento del usuario'),
       ('GET_USER_ACCESSIBLE_COLLECTIONS', 'Listar colecciones documentales accesibles para el usuario'),
       ('GET_USER_ACCESSIBLE_DOCUMENTS', 'Listar documentos accesibles para el usuario según su perfil MAC'),

       -- ============================================================
       -- aura-llm-service
       -- ============================================================
       ('LLM_DOCUMENT_QUESTION', 'Pregunta LLM contra documentación'),
       ('LLM_DOCUMENT_SUMMARY', 'Resumen de documento mediante LLM'),
       ('LLM_DOCUMENT_ACTION', 'Acción automatizada sobre documento'),
       ('LLM_AGENT', 'Ejecución de agentes LLM'),
       ('LLM_DOCUMENT_CLASSIFY', 'Clasificación de documentos vía LLM'),
       ('LLM_FRAGMENT_ENRICH', 'Enriquecimiento de fragmentos'),
       ('LLM_GRAPH_EXTRACTION', 'Extracción de grafo vía LLM'),
       ('LLM_GRAPH_QUERY_TRANSLATION', 'Traducción de consulta a grafo'),
       ('LLM_GENERAL_CHAT', 'Chat general con LLM sin contexto documental'),
       ('LLM_REPORT_GENERATE', 'Generación de reporte mediante LLM'),
       ('LLM_CHECKLIST_GENERATE', 'Generación de checklist mediante LLM'),
       ('LLM_TIMELINE_GENERATE', 'Generación de línea de tiempo mediante LLM'),
       ('LLM_QUIZ_GENERATE', 'Generación de quiz mediante LLM'),
       ('LLM_LESSONS_LEARNED_GENERATE', 'Generación de lecciones aprendidas mediante LLM'),
       ('LLM_DECISION_BRIEF_GENERATE', 'Generación de decision brief mediante LLM'),
       ('LLM_DOCUMENT_SUMMARY_GENERATE', 'Generación de resumen de documentos mediante LLM'),
       ('LLM_DOCUMENT_ACTION_GENERATE', 'Generación de acción sobre documentos mediante LLM'),

       -- ============================================================
       -- aura-chat-service
       -- ============================================================
       ('MANAGE_CHATS', 'Listar todos los chats (admin)'),
       ('LIST_CHATS', 'Listar chats'),
       ('LIST_MY_CHATS', 'Listar chats creados por el usuario'),
       ('LIST_ARCHIVED_CHATS', 'Listar chats archivados para el usuario'),
       ('CREATE_CHAT', 'Crear chat'),
       ('GET_CHAT', 'Ver chat'),
       ('UPDATE_CHAT', 'Actualizar chat'),
       ('DELETE_CHAT', 'Eliminar chat'),
       ('PIN_CHAT', 'Fijar/desfijar chat en lista'),
       ('ARCHIVE_CHAT', 'Archivar chats'),
       ('UNARCHIVE_CHAT', 'Desarchivar chats'),
       ('LOCK_CHAT', 'Bloquear envío en chat'),
       ('LIST_SHARE_LINKS', 'Listar enlaces de compartición'),
       ('CREATE_SHARE_LINK', 'Crear enlace de compartición'),
       ('DELETE_SHARE_LINK', 'Eliminar enlace de compartición'),
       ('LIST_MEMBERS', 'Listar miembros del chat'),
       ('LIST_MY_MEMBERSHIPS', 'Listar mis membresías'),
       ('ADD_MEMBER', 'Invitar miembro al chat'),
       ('UPDATE_MEMBER', 'Actualizar miembro'),
       ('REMOVE_MEMBER', 'Eliminar miembro'),
       ('LEAVE_CHAT', 'Salir del chat'),
       ('UPDATE_MEMBER_ROLE', 'Actualizar rol de miembro'),
       ('MANAGE_MEMBERS', 'Listar miembros de cualquier chat (admin)'),
       ('LIST_MESSAGES', 'Listar mensajes'),
       ('MANAGE_MESSAGES', 'Ver historial de mensajes de cualquier chat (admin)'),
       ('SEND_MESSAGE', 'Enviar mensaje'),
       ('DELETE_MESSAGE', 'Eliminar mensaje'),
       ('CLEAR_CHAT_HISTORY', 'Limpiar historial del chat'),
       ('MARK_CHAT_AS_READ', 'Marcar chat como leído'),
       ('REGENERATE_AI_RESPONSE', 'Regenerar respuesta IA'),
       ('LIST_BOOKMARKS', 'Listar marcadores'),
       ('BOOKMARK_MESSAGE', 'Marcar/desmarcar mensaje como favorito'),
       ('LIST_PINNED_MESSAGES', 'Listar mensajes fijados'),
       ('PIN_MESSAGE', 'Fijar mensaje'),
       ('SET_MESSAGE_FEEDBACK', 'Feedback sobre mensaje del asistente'),
       ('LIST_THREAD_REPLIES', 'Listar respuestas de hilo'),
       ('ADD_THREAD_REPLY', 'Añadir respuesta en hilo'),
       ('EDIT_THREAD_REPLY', 'Editar respuesta propia en hilo'),
       ('DELETE_THREAD_REPLY', 'Eliminar respuesta propia en hilo'),
       ('EXPORT_MESSAGE', 'Exportar mensaje individual'),
       ('EXPORT_CHAT', 'Exportar chat o mensaje'),
       ('LIST_REPORTS', 'Listar reportes'),
       ('CREATE_REPORT', 'Crear reporte'),
       ('GET_REPORT', 'Ver detalle de reporte'),
       ('UPDATE_REPORT', 'Actualizar reporte'),
       ('DELETE_REPORT', 'Eliminar reporte'),
       ('EXPORT_REPORT', 'Exportar reporte'),
       ('LIST_CHECKLISTS', 'Listar checklists'),
       ('CREATE_CHECKLIST', 'Crear checklist'),
       ('GET_CHECKLIST', 'Ver detalle de checklist'),
       ('UPDATE_CHECKLIST', 'Actualizar checklist'),
       ('DELETE_CHECKLIST', 'Eliminar checklist'),
       ('EXPORT_CHECKLIST', 'Exportar checklist'),
       ('MANAGE_REPORTS', 'Listar todos los informes (admin)'),
       ('MANAGE_EXPORT_REPORT', 'Exportar cualquier informe (admin)'),
       ('MANAGE_CHECKLISTS', 'Listar todas las checklists (admin)'),
       ('MANAGE_EXPORT_CHECKLIST', 'Exportar cualquier checklist (admin)'),
       ('LIST_TIMELINES', 'Listar líneas de tiempo'),
       ('CREATE_TIMELINE', 'Crear línea de tiempo'),
       ('GET_TIMELINE', 'Ver detalle de línea de tiempo'),
       ('UPDATE_TIMELINE', 'Actualizar línea de tiempo'),
       ('DELETE_TIMELINE', 'Eliminar línea de tiempo'),
       ('EXPORT_TIMELINE', 'Exportar línea de tiempo'),
       ('MANAGE_TIMELINES', 'Listar todas las líneas de tiempo (admin)'),
       ('MANAGE_EXPORT_TIMELINE', 'Exportar cualquier línea de tiempo (admin)'),
       ('LIST_QUIZZES', 'Listar quizzes'),
       ('CREATE_QUIZ', 'Crear quiz'),
       ('GET_QUIZ', 'Ver detalle de quiz'),
       ('UPDATE_QUIZ', 'Actualizar quiz'),
       ('DELETE_QUIZ', 'Eliminar quiz'),
       ('EXPORT_QUIZ', 'Exportar quiz'),
       ('MANAGE_QUIZZES', 'Listar todos los quizzes (admin)'),
       ('MANAGE_EXPORT_QUIZ', 'Exportar cualquier quiz (admin)'),
       ('LIST_LESSONS_LEARNED', 'Listar lecciones aprendidas'),
       ('CREATE_LESSONS_LEARNED', 'Crear lecciones aprendidas'),
       ('GET_LESSONS_LEARNED', 'Ver detalle de lecciones aprendidas'),
       ('UPDATE_LESSONS_LEARNED', 'Actualizar lecciones aprendidas'),
       ('DELETE_LESSONS_LEARNED', 'Eliminar lecciones aprendidas'),
       ('EXPORT_LESSONS_LEARNED', 'Exportar lecciones aprendidas'),
       ('MANAGE_LESSONS_LEARNED', 'Listar todas las lecciones aprendidas (admin)'),
       ('MANAGE_EXPORT_LESSONS_LEARNED', 'Exportar cualquier lección aprendida (admin)'),
       ('LIST_DECISION_BRIEFS', 'Listar decision briefs'),
       ('CREATE_DECISION_BRIEF', 'Crear decision brief'),
       ('GET_DECISION_BRIEF', 'Ver detalle de decision brief'),
       ('UPDATE_DECISION_BRIEF', 'Actualizar decision brief'),
       ('DELETE_DECISION_BRIEF', 'Eliminar decision brief'),
       ('EXPORT_DECISION_BRIEF', 'Exportar decision brief'),
       ('MANAGE_DECISION_BRIEFS', 'Listar todos los decision briefs (admin)'),
       ('MANAGE_EXPORT_DECISION_BRIEF', 'Exportar cualquier decision brief (admin)'),
       ('LIST_DOCUMENT_SUMMARIES', 'Listar resúmenes de documentos'),
       ('GET_DOCUMENT_SUMMARY', 'Ver detalle de resumen de documentos'),
       ('UPDATE_DOCUMENT_SUMMARY', 'Actualizar resumen de documentos'),
       ('DELETE_DOCUMENT_SUMMARY', 'Eliminar resumen de documentos'),
       ('EXPORT_DOCUMENT_SUMMARY', 'Exportar resumen de documentos'),
       ('MANAGE_DOCUMENT_SUMMARIES', 'Listar todos los resúmenes de documentos (admin)'),
       ('MANAGE_EXPORT_DOCUMENT_SUMMARY', 'Exportar cualquier resumen de documentos (admin)'),
       ('LIST_DOCUMENT_ACTIONS', 'Listar acciones sobre documentos'),
       ('GET_DOCUMENT_ACTION', 'Ver detalle de acción sobre documentos'),
       ('UPDATE_DOCUMENT_ACTION', 'Actualizar acción sobre documentos'),
       ('DELETE_DOCUMENT_ACTION', 'Eliminar acción sobre documentos'),
       ('EXPORT_DOCUMENT_ACTION', 'Exportar acción sobre documentos'),
       ('MANAGE_DOCUMENT_ACTIONS', 'Listar todas las acciones sobre documentos (admin)'),
       ('MANAGE_EXPORT_DOCUMENT_ACTION', 'Exportar cualquier acción sobre documentos (admin)'),
       ('VIEW_FEEDBACK_ANALYTICS', 'Ver analítica de feedback (admin)'),
       ('LIST_ARTIFACTS', 'Listar artefactos'),
       ('CREATE_ARTIFACT', 'Crear artefacto'),
       ('GET_ARTIFACT', 'Ver detalle de artefacto'),
       ('UPDATE_ARTIFACT', 'Actualizar artefacto'),
       ('DELETE_ARTIFACT', 'Eliminar artefacto'),
       ('LIST_ARTIFACT_VERSIONS', 'Listar versiones de un artefacto'),
       ('MANAGE_ARTIFACTS', 'Listar todos los artefactos (admin)'),
       ('LIST_ASSISTANTS', 'Listar asistentes'),
       ('GET_ASSISTANT', 'Ver detalle de asistente'),
       ('USE_ASSISTANT', 'Usar asistente'),
       ('CREATE_ASSISTANT', 'Crear asistente'),
       ('UPDATE_ASSISTANT', 'Actualizar asistente'),
       ('DELETE_ASSISTANT', 'Eliminar asistente'),
       ('MANAGE_ASSISTANTS', 'Gestión general de asistentes'),

       -- ============================================================
       -- aura-notification-service
       -- ============================================================
       ('NOTIFICATION_INBOX_LIST', 'Listar bandeja de notificaciones del propio usuario'),
       ('NOTIFICATION_UNREAD_COUNT_GET', 'Consultar contador de notificaciones no leídas'),
       ('NOTIFICATION_STREAM_SUBSCRIBE', 'Suscribirse al stream SSE de notificaciones del propio usuario'),
       ('NOTIFICATION_DETAIL_GET', 'Ver detalle de una notificación propia'),
       ('NOTIFICATION_STATUS_PATCH', 'Marcar notificación propia como leída / no leída / archivada'),
       ('NOTIFICATION_SOFT_DELETE', 'Borrado lógico de una notificación propia'),
       ('NOTIFICATION_MARK_ALL_READ_POST', 'Marcar todas las notificaciones propias como leídas'),
       ('NOTIFICATION_PREFERENCES_GLOBAL_GET', 'Ver preferencias globales de notificación del propio usuario'),
       ('NOTIFICATION_PREFERENCES_GLOBAL_PUT', 'Actualizar preferencias globales de notificación del propio usuario'),
       ('NOTIFICATION_PREFERENCES_EVENT_TYPES_GET', 'Ver matriz de canales por tipo de evento del propio usuario'),
       ('NOTIFICATION_PREFERENCES_EVENT_TYPE_PUT', 'Actualizar canales para un tipo de evento del propio usuario');

-- ============================================================
-- aura-auth-service admin panel permissions
-- ============================================================
INSERT INTO permission (name, description)
VALUES
       ('ADMIN_DASHBOARD_VIEW',     'Ver dashboard administrativo'),
       ('ADMIN_USERS_VIEW',         'Ver listado de usuarios regulares en el panel'),
       ('ADMIN_USERS_VIEW_ADMINS',  'Ver usuarios administradores en el panel'),
       ('ADMIN_USERS_CREATE',       'Crear usuarios regulares en el panel'),
       ('ADMIN_USERS_CREATE_ADMIN', 'Crear usuarios administradores'),
       ('ADMIN_USERS_EDIT',         'Editar usuarios regulares en el panel'),
       ('ADMIN_USERS_EDIT_ADMIN',   'Editar usuarios administradores'),
       ('ADMIN_USERS_DELETE',       'Eliminar usuarios regulares en el panel'),
       ('ADMIN_USERS_DELETE_ADMIN', 'Eliminar usuarios administradores'),
       ('ADMIN_USERS_MAC',          'Gestionar perfil MAC de usuarios regulares'),
       ('ADMIN_GROUPS_MANAGE',      'Gestionar grupos en el panel'),
       ('ADMIN_ROLES_VIEW',         'Ver roles, permisos y asignaciones'),
       ('ADMIN_ROLES_EDIT',         'Editar asignación de permisos a roles'),
       ('ADMIN_AUDIT_VIEW',         'Ver registro de auditoría de acciones de admins'),
       ('ADMIN_AUDIT_VIEW_ALL',     'Ver registro de auditoría completo'),
       ('ADMIN_MAC_MANAGE',         'Gestionar niveles de clasificación y agrupaciones'),
       ('ADMIN_MAC_USER_PROFILE',   'Ver y editar perfil MAC dedicado de usuarios'),
       ('ADMIN_CHAT_VIEW',          'Ver y gestionar todos los chats en el panel'),
       ('ADMIN_ELEVATE',            'Elevar privilegios temporales a superadmin');

INSERT INTO role (name, description)
VALUES ('superadmin', 'Super administrador con acceso total'),
       ('admin', 'Administrador con acceso de gestión'),
       ('user', 'Usuario estándar del sistema');

INSERT INTO permission_in_role (role_id, permission_id)
SELECT r.id, p.id
FROM role r
         JOIN permission p ON TRUE
WHERE r.name = 'superadmin';

-- admin: explicit grant — all existing service permissions + shared ADMIN_* panel permissions.
-- Superadmin-only ADMIN_* permissions are intentionally excluded.
INSERT INTO permission_in_role (role_id, permission_id)
SELECT r.id, p.id
FROM role r
         JOIN permission p ON p.name IN (
    -- ── aura-document-processing-service ─────────────────────────────────────
    'INGEST_DOCUMENT',
    'GET_DOCUMENT',
    'LIST_DOCUMENTS',
    'LIST_DOCUMENTS_BY_CHAT',
    'DOWNLOAD_DOCUMENT',
    'DOWNLOAD_DOCUMENT_ADMIN',
    'SOFT_DELETE_DOCUMENT',
    'SOFT_DELETE_DOCUMENTS_BY_CHAT',
    'POST_PROCESS_DOCUMENTS_START_ALL',
    'POST_PROCESS_DOCUMENTS_START',
    'POST_PROCESS_DOCUMENTS_STATUS',
    'POST_PROCESS_DOCUMENTS_STOP',
    'POST_PROCESS_FRAGMENTS_START_ALL',
    'POST_PROCESS_FRAGMENTS_START',
    'POST_PROCESS_FRAGMENTS_STATUS',
    'POST_PROCESS_FRAGMENTS_STOP',
    'LIST_CONTEXT_FRAGMENTS_BY_QUESTION',
    'LIST_CONTEXT_FRAGMENTS_BY_DOCUMENTS',
    'SEARCH_DOCUMENTS_BY_CONTENT',
    'GRAPH_QUERY',
    'GRAPH_ENTITY',
    'GRAPH_PATH',
    -- ── aura-document-collection-service ─────────────────────────────────────
    'LIST_DOCUMENT_COLLECTIONS',
    'CREATE_DOCUMENT_COLLECTION',
    'GET_DOCUMENT_COLLECTION',
    'UPDATE_DOCUMENT_COLLECTION',
    'DELETE_DOCUMENT_COLLECTION',
    'LIST_DOCUMENT_COLLECTION_DOCUMENTS',
    'ADD_DOCUMENT_COLLECTION_DOCUMENT',
    'REMOVE_DOCUMENT_COLLECTION_DOCUMENT',
    'LIST_CLASSIFICATION_LEVELS',
    'CREATE_CLASSIFICATION_LEVEL',
    'GET_CLASSIFICATION_LEVEL',
    'UPDATE_CLASSIFICATION_LEVEL',
    'DELETE_CLASSIFICATION_LEVEL',
    'LIST_COMPARTMENTS',
    'CREATE_COMPARTMENT',
    'GET_COMPARTMENT',
    'UPDATE_COMPARTMENT',
    'DELETE_COMPARTMENT',
    'GET_USER_AUTHORIZATION',
    'SET_USER_CLEARANCE',
    'DELETE_USER_CLEARANCE',
    'LIST_USER_COMPARTMENTS',
    'ADD_USER_COMPARTMENT',
    'REMOVE_USER_COMPARTMENT',
    'GET_USER_ACCESSIBLE_COLLECTIONS',
    'GET_USER_ACCESSIBLE_DOCUMENTS',
    -- ── aura-llm-service ─────────────────────────────────────────────────────
    'LLM_DOCUMENT_QUESTION',
    'LLM_DOCUMENT_SUMMARY',
    'LLM_DOCUMENT_ACTION',
    'LLM_AGENT',
    'LLM_DOCUMENT_CLASSIFY',
    'LLM_FRAGMENT_ENRICH',
    'LLM_GRAPH_EXTRACTION',
    'LLM_GRAPH_QUERY_TRANSLATION',
    'LLM_GENERAL_CHAT',
    'LLM_REPORT_GENERATE',
    'LLM_CHECKLIST_GENERATE',
    'LLM_TIMELINE_GENERATE',
    'LLM_QUIZ_GENERATE',
    'LLM_LESSONS_LEARNED_GENERATE',
    'LLM_DECISION_BRIEF_GENERATE',
    'LLM_DOCUMENT_SUMMARY_GENERATE',
    'LLM_DOCUMENT_ACTION_GENERATE',
    -- ── aura-chat-service ─────────────────────────────────────────────────────
    'MANAGE_CHATS',
    'LIST_CHATS',
    'LIST_MY_CHATS',
    'LIST_ARCHIVED_CHATS',
    'CREATE_CHAT',
    'GET_CHAT',
    'UPDATE_CHAT',
    'DELETE_CHAT',
    'PIN_CHAT',
    'ARCHIVE_CHAT',
    'UNARCHIVE_CHAT',
    'LOCK_CHAT',
    'LIST_SHARE_LINKS',
    'CREATE_SHARE_LINK',
    'DELETE_SHARE_LINK',
    'LIST_MEMBERS',
    'LIST_MY_MEMBERSHIPS',
    'ADD_MEMBER',
    'UPDATE_MEMBER',
    'REMOVE_MEMBER',
    'LEAVE_CHAT',
    'UPDATE_MEMBER_ROLE',
    'MANAGE_MEMBERS',
    'LIST_MESSAGES',
    'MANAGE_MESSAGES',
    'SEND_MESSAGE',
    'DELETE_MESSAGE',
    'CLEAR_CHAT_HISTORY',
    'MARK_CHAT_AS_READ',
    'REGENERATE_AI_RESPONSE',
    'LIST_BOOKMARKS',
    'BOOKMARK_MESSAGE',
    'LIST_PINNED_MESSAGES',
    'PIN_MESSAGE',
    'SET_MESSAGE_FEEDBACK',
    'LIST_THREAD_REPLIES',
    'ADD_THREAD_REPLY',
    'EDIT_THREAD_REPLY',
    'DELETE_THREAD_REPLY',
    'EXPORT_MESSAGE',
    'EXPORT_CHAT',
    'LIST_REPORTS',
    'CREATE_REPORT',
    'GET_REPORT',
    'UPDATE_REPORT',
    'DELETE_REPORT',
    'EXPORT_REPORT',
    'LIST_CHECKLISTS',
    'CREATE_CHECKLIST',
    'GET_CHECKLIST',
    'UPDATE_CHECKLIST',
    'DELETE_CHECKLIST',
    'EXPORT_CHECKLIST',
    'MANAGE_REPORTS',
    'MANAGE_EXPORT_REPORT',
    'MANAGE_CHECKLISTS',
    'MANAGE_EXPORT_CHECKLIST',
    'LIST_TIMELINES',
    'CREATE_TIMELINE',
    'GET_TIMELINE',
    'UPDATE_TIMELINE',
    'DELETE_TIMELINE',
    'EXPORT_TIMELINE',
    'MANAGE_TIMELINES',
    'MANAGE_EXPORT_TIMELINE',
    'LIST_QUIZZES',
    'CREATE_QUIZ',
    'GET_QUIZ',
    'UPDATE_QUIZ',
    'DELETE_QUIZ',
    'EXPORT_QUIZ',
    'MANAGE_QUIZZES',
    'MANAGE_EXPORT_QUIZ',
    'LIST_LESSONS_LEARNED',
    'CREATE_LESSONS_LEARNED',
    'GET_LESSONS_LEARNED',
    'UPDATE_LESSONS_LEARNED',
    'DELETE_LESSONS_LEARNED',
    'EXPORT_LESSONS_LEARNED',
    'MANAGE_LESSONS_LEARNED',
    'MANAGE_EXPORT_LESSONS_LEARNED',
    'LIST_DECISION_BRIEFS',
    'CREATE_DECISION_BRIEF',
    'GET_DECISION_BRIEF',
    'UPDATE_DECISION_BRIEF',
    'DELETE_DECISION_BRIEF',
    'EXPORT_DECISION_BRIEF',
    'MANAGE_DECISION_BRIEFS',
    'MANAGE_EXPORT_DECISION_BRIEF',
    'LIST_DOCUMENT_SUMMARIES',
    'GET_DOCUMENT_SUMMARY',
    'UPDATE_DOCUMENT_SUMMARY',
    'DELETE_DOCUMENT_SUMMARY',
    'EXPORT_DOCUMENT_SUMMARY',
    'MANAGE_DOCUMENT_SUMMARIES',
    'MANAGE_EXPORT_DOCUMENT_SUMMARY',
    'LIST_DOCUMENT_ACTIONS',
    'GET_DOCUMENT_ACTION',
    'UPDATE_DOCUMENT_ACTION',
    'DELETE_DOCUMENT_ACTION',
    'EXPORT_DOCUMENT_ACTION',
    'MANAGE_DOCUMENT_ACTIONS',
    'MANAGE_EXPORT_DOCUMENT_ACTION',
    'VIEW_FEEDBACK_ANALYTICS',
    'LIST_ARTIFACTS',
    'CREATE_ARTIFACT',
    'GET_ARTIFACT',
    'UPDATE_ARTIFACT',
    'DELETE_ARTIFACT',
    'LIST_ARTIFACT_VERSIONS',
    'MANAGE_ARTIFACTS',
    'LIST_ASSISTANTS',
    'GET_ASSISTANT',
    'USE_ASSISTANT',
    'CREATE_ASSISTANT',
    'UPDATE_ASSISTANT',
    'DELETE_ASSISTANT',
    'MANAGE_ASSISTANTS',
    -- ── aura-notification-service ─────────────────────────────────────────────
    'NOTIFICATION_INBOX_LIST',
    'NOTIFICATION_UNREAD_COUNT_GET',
    'NOTIFICATION_STREAM_SUBSCRIBE',
    'NOTIFICATION_DETAIL_GET',
    'NOTIFICATION_STATUS_PATCH',
    'NOTIFICATION_SOFT_DELETE',
    'NOTIFICATION_MARK_ALL_READ_POST',
    'NOTIFICATION_PREFERENCES_GLOBAL_GET',
    'NOTIFICATION_PREFERENCES_GLOBAL_PUT',
    'NOTIFICATION_PREFERENCES_EVENT_TYPES_GET',
    'NOTIFICATION_PREFERENCES_EVENT_TYPE_PUT',
    -- ── aura-auth-service admin panel (shared: admin + superadmin) ────────────
    'ADMIN_DASHBOARD_VIEW',
    'ADMIN_USERS_VIEW',
    'ADMIN_USERS_CREATE',
    'ADMIN_USERS_EDIT',
    'ADMIN_USERS_DELETE',
    'ADMIN_USERS_MAC',
    'ADMIN_GROUPS_MANAGE',
    'ADMIN_ROLES_VIEW',
    'ADMIN_AUDIT_VIEW',
    'ADMIN_MAC_MANAGE',
    'ADMIN_ELEVATE'
    -- NOT included (superadmin-only):
    -- 'ADMIN_USERS_VIEW_ADMINS', 'ADMIN_USERS_CREATE_ADMIN',
    -- 'ADMIN_USERS_EDIT_ADMIN',  'ADMIN_USERS_DELETE_ADMIN',
    -- 'ADMIN_ROLES_EDIT',        'ADMIN_AUDIT_VIEW_ALL',
    -- 'ADMIN_MAC_USER_PROFILE',  'ADMIN_CHAT_VIEW'
)
WHERE r.name = 'admin';

INSERT INTO permission_in_role (role_id, permission_id)
SELECT r.id, p.id
FROM role r
         JOIN permission p ON p.name IN (
                                         'DOCUMENT_CREATE',
                                         'DOCUMENT_QUERY',
                                         'DOCUMENT_DELETE',
                                         'DOCUMENT_DOWNLOAD',
                                         'DOCUMENT_SEARCH',
                                         'FRAGMENT_QUERY',
                                         'GRAPH_QUERY',
                                         'GRAPH_ENTITY',
                                         'GRAPH_PATH',
                                         'GRAPH_SEARCH',
                                         'GRAPH_ONTOLOGY',
                                         'LLM_DOCUMENT_QUESTION',
                                         'LLM_DOCUMENT_SUMMARY',
                                         'LLM_DOCUMENT_ACTION',
                                         'LLM_AGENT',
                                         'LLM_DOCUMENT_CLASSIFY',
                                         'LLM_FRAGMENT_ENRICH',
                                         'LLM_GRAPH_EXTRACTION',
                                         'LLM_GRAPH_QUERY_TRANSLATION',
                                         'LLM_GENERAL_CHAT',
                                         'LLM_REPORT_GENERATE',
                                         'LLM_CHECKLIST_GENERATE',
                                         'LLM_TIMELINE_GENERATE',
                                         'LLM_QUIZ_GENERATE',
                                         'LLM_LESSONS_LEARNED_GENERATE',
                                         'LLM_DECISION_BRIEF_GENERATE',
                                         'LLM_DOCUMENT_SUMMARY_GENERATE',
                                         'LLM_DOCUMENT_ACTION_GENERATE',
                                         'GET_USER_ACCESSIBLE_COLLECTIONS',
                                         'GET_USER_ACCESSIBLE_DOCUMENTS',
                                         'LIST_CHATS',
                                         'LIST_MY_CHATS',
                                         'LIST_ARCHIVED_CHATS',
                                         'CREATE_CHAT',
                                         'GET_CHAT',
                                         'UPDATE_CHAT',
                                         'DELETE_CHAT',
                                         'PIN_CHAT',
                                         'ARCHIVE_CHAT',
                                         'UNARCHIVE_CHAT',
                                         'LOCK_CHAT',
                                         'LIST_SHARE_LINKS',
                                         'CREATE_SHARE_LINK',
                                         'DELETE_SHARE_LINK',
                                         'LIST_MEMBERS',
                                         'LIST_MY_MEMBERSHIPS',
                                         'ADD_MEMBER',
                                         'UPDATE_MEMBER',
                                         'REMOVE_MEMBER',
                                         'LEAVE_CHAT',
                                         'UPDATE_MEMBER_ROLE',
                                         'LIST_MESSAGES',
                                         'SEND_MESSAGE',
                                         'DELETE_MESSAGE',
                                         'CLEAR_CHAT_HISTORY',
                                         'MARK_CHAT_AS_READ',
                                         'REGENERATE_AI_RESPONSE',
                                         'LIST_BOOKMARKS',
                                         'BOOKMARK_MESSAGE',
                                         'LIST_PINNED_MESSAGES',
                                         'PIN_MESSAGE',
                                         'SET_MESSAGE_FEEDBACK',
                                         'LIST_THREAD_REPLIES',
                                         'ADD_THREAD_REPLY',
                                         'EDIT_THREAD_REPLY',
                                         'DELETE_THREAD_REPLY',
                                         'EXPORT_MESSAGE',
                                         'EXPORT_CHAT',
                                         'LIST_REPORTS',
                                         'GET_REPORT',
                                         'UPDATE_REPORT',
                                         'DELETE_REPORT',
                                         'EXPORT_REPORT',
                                         'LIST_CHECKLISTS',
                                         'GET_CHECKLIST',
                                         'UPDATE_CHECKLIST',
                                         'DELETE_CHECKLIST',
                                         'EXPORT_CHECKLIST',
                                         'LIST_TIMELINES',
                                         'GET_TIMELINE',
                                         'UPDATE_TIMELINE',
                                         'DELETE_TIMELINE',
                                         'EXPORT_TIMELINE',
                                         'LIST_QUIZZES',
                                         'GET_QUIZ',
                                         'UPDATE_QUIZ',
                                         'DELETE_QUIZ',
                                         'EXPORT_QUIZ',
                                         'LIST_LESSONS_LEARNED',
                                         'GET_LESSONS_LEARNED',
                                         'UPDATE_LESSONS_LEARNED',
                                         'DELETE_LESSONS_LEARNED',
                                         'EXPORT_LESSONS_LEARNED',
                                         'LIST_DECISION_BRIEFS',
                                         'GET_DECISION_BRIEF',
                                         'UPDATE_DECISION_BRIEF',
                                         'DELETE_DECISION_BRIEF',
                                         'EXPORT_DECISION_BRIEF',
                                         'LIST_DOCUMENT_SUMMARIES',
                                         'GET_DOCUMENT_SUMMARY',
                                         'UPDATE_DOCUMENT_SUMMARY',
                                         'DELETE_DOCUMENT_SUMMARY',
                                         'EXPORT_DOCUMENT_SUMMARY',
                                         'LIST_DOCUMENT_ACTIONS',
                                         'GET_DOCUMENT_ACTION',
                                         'UPDATE_DOCUMENT_ACTION',
                                         'DELETE_DOCUMENT_ACTION',
                                         'EXPORT_DOCUMENT_ACTION',
                                         'LIST_ARTIFACTS',
                                         'CREATE_ARTIFACT',
                                         'GET_ARTIFACT',
                                         'UPDATE_ARTIFACT',
                                         'DELETE_ARTIFACT',
                                         'LIST_ARTIFACT_VERSIONS',
                                         'LIST_ASSISTANTS',
                                         'GET_ASSISTANT',
                                         'USE_ASSISTANT',
                                         'NOTIFICATION_INBOX_LIST',
                                         'NOTIFICATION_UNREAD_COUNT_GET',
                                         'NOTIFICATION_STREAM_SUBSCRIBE',
                                         'NOTIFICATION_DETAIL_GET',
                                         'NOTIFICATION_STATUS_PATCH',
                                         'NOTIFICATION_SOFT_DELETE',
                                         'NOTIFICATION_MARK_ALL_READ_POST',
                                         'NOTIFICATION_PREFERENCES_GLOBAL_GET',
                                         'NOTIFICATION_PREFERENCES_GLOBAL_PUT',
                                         'NOTIFICATION_PREFERENCES_EVENT_TYPES_GET',
                                         'NOTIFICATION_PREFERENCES_EVENT_TYPE_PUT'
    )
WHERE r.name = 'user';

INSERT INTO auth_user (username, email, password, status,
                       account_non_expired, account_non_locked, credentials_non_expired,
                       enabled, failed_login_attempts,
                       created_by, created_at)
VALUES ('gral.rodriguez',
        'rodriguez@faa.mil.ar',
        'pbkdf2_sha256$870000$ttIbmJgVlcTGVjHOBExZWi$ruSK+kg8xVYNkOtoTWniZLbv7US5+algGX7gT68PPKs=',
        'active', true, true, true, true, 0,
        1, NOW()),
       ('como.martinez',
        'martinez@faa.mil.ar',
        'pbkdf2_sha256$870000$ttIbmJgVlcTGVjHOBExZWi$ruSK+kg8xVYNkOtoTWniZLbv7US5+algGX7gT68PPKs=',
        'active', true, true, true, true, 0,
        1, NOW()),
       ('cap.gonzalez',
        'gonzalez@faa.mil.ar',
        'pbkdf2_sha256$870000$ttIbmJgVlcTGVjHOBExZWi$ruSK+kg8xVYNkOtoTWniZLbv7US5+algGX7gT68PPKs=',
        'active', true, true, true, true, 0,
        1, NOW()),
       ('ten.lopez',
        'lopez@faa.mil.ar',
        'pbkdf2_sha256$870000$ttIbmJgVlcTGVjHOBExZWi$ruSK+kg8xVYNkOtoTWniZLbv7US5+algGX7gT68PPKs=',
        'active', true, true, true, true, 0,
        1, NOW()),
       ('cabo.perez',
        'perez@faa.mil.ar',
        'pbkdf2_sha256$870000$ttIbmJgVlcTGVjHOBExZWi$ruSK+kg8xVYNkOtoTWniZLbv7US5+algGX7gT68PPKs=',
        'active', true, true, true, true, 0,
        1, NOW()),
       ('sold.garcia',
        'garcia@faa.mil.ar',
        'pbkdf2_sha256$870000$ttIbmJgVlcTGVjHOBExZWi$ruSK+kg8xVYNkOtoTWniZLbv7US5+algGX7gT68PPKs=',
        'active', true, true, true, true, 0,
        1, NOW());

INSERT INTO auth_user_in_role (auth_user_id, role_id, created_by, created_at)
VALUES ((SELECT id FROM auth_user WHERE username = 'gral.rodriguez'),
        (SELECT id FROM role WHERE name = 'superadmin'),
        1, NOW()),
       ((SELECT id FROM auth_user WHERE username = 'como.martinez'),
        (SELECT id FROM role WHERE name = 'admin'),
        1, NOW()),
       ((SELECT id FROM auth_user WHERE username = 'cap.gonzalez'),
        (SELECT id FROM role WHERE name = 'admin'),
        1, NOW()),
       ((SELECT id FROM auth_user WHERE username = 'ten.lopez'),
        (SELECT id FROM role WHERE name = 'user'),
        1, NOW()),
       ((SELECT id FROM auth_user WHERE username = 'cabo.perez'),
        (SELECT id FROM role WHERE name = 'user'),
        1, NOW()),
       ((SELECT id FROM auth_user WHERE username = 'sold.garcia'),
        (SELECT id FROM role WHERE name = 'user'),
        1, NOW());
