[tool:pytest]
DJANGO_SETTINGS_MODULE = configuration.settings
python_files = tests.py test_*.py *_tests.py
testpaths = tests

[flake8]
max-line-length = 100
exclude = .git,__pycache__,venv,migrations
ignore = E203,W503

[isort]
profile = django
line_length = 100
skip_gitignore = True
