[pytest]
DJANGO_SETTINGS_MODULE = aura_auth_service.settings.test
python_files = tests/unitarios/test_*.py tests/integracion/test_*.py
python_classes = Test*
python_functions = test_*
addopts = --reuse-db
