services:


  mock-auth:
    build: ../../mock-auth
    container_name: mock-auth
    ports:
      - "8080:8000"

  llm:
    build:
      context: ../llm
      dockerfile: Dockerfile
    container_name: llm
    env_file:
      - ../../aura-llm-service/.env.docker
      - ../../aura-document-processing-service/.env.docker
    volumes:
      - llm_data:/root/.ollama
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434"]
      interval: 60s
      timeout: 10s
      retries: 10
      start_period: 30s

volumes:
  llm_data:
