from typing import Final

MAX_ID: Final[int] = 2_147_483_647

MAX_NAME_CHARS: Final[int] = 255
MAX_DESCRIPTION_CHARS: Final[int] = 2_000
MAX_CATEGORY_CHARS: Final[int] = 100
MAX_STORAGE_URL_CHARS: Final[int] = 1_024
MAX_MIME_TYPE_CHARS: Final[int] = 256
MIN_FILE_SIZE_BYTES: Final[int] = 1
MAX_DOCUMENTS_IN_LIST: Final[int] = 10_000

# Maximum number of files accepted in a single bulk-create upload request.
MAX_BULK_CREATE_DOCUMENTS: Final[int] = 50

DEFAULT_DOCUMENT_QUERY_PAGE_SIZE: Final[int] = 20
MAX_DOCUMENT_QUERY_PAGE_SIZE: Final[int] = 100

MAX_ENTITY_NAME_CHARS: Final[int] = 200
MAX_PATH_HOPS: Final[int] = 6

MAX_FRAGMENT_CONTENT_CHARS: Final[int] = 50_000
MAX_FRAGMENT_SUMMARY_CHARS: Final[int] = 50_000
MAX_CONTENT_CHARS: Final[int] = 50_000
MAX_SUMMARY_CHARS: Final[int] = 10_000
MAX_TOPIC_CHARS: Final[int] = 500
MAX_ENTITY_KEY_CHARS: Final[int] = 255
MAX_ENTITY_VALUE_CHARS: Final[int] = 1_000
MAX_ENTITY_KEYS: Final[int] = 200
MAX_TOPICS: Final[int] = 100
MAX_FRAGMENT_INDEX: Final[int] = 100_000
MAX_FRAGMENTS_IN_LIST: Final[int] = 1_000
MAX_TOTAL_FRAGMENTS_LIST_CHARS: Final[int] = 300_000

MAX_DOCUMENT_SEARCH_QUERY_CHARS: Final[int] = 1_000
MAX_DOCUMENT_SEARCH_RESULTS: Final[int] = 50
DEFAULT_DOCUMENT_SEARCH_RESULTS: Final[int] = 10
MAX_DOCUMENT_SEARCH_SNIPPET_CHARS: Final[int] = 500

DEFAULT_DOCUMENT_SEARCH_PAGE_SIZE: Final[int] = 10
MAX_DOCUMENT_SEARCH_PAGE_SIZE: Final[int] = 50
MAX_DOCUMENT_SEARCH_PAGE: Final[int] = 200
MAX_DOCUMENT_SEARCH_CANDIDATE_POOL: Final[int] = 5_000

MAX_CHARS_PER_QUERY: Final[int] = 16_000
MAX_QUERIES_PER_TYPE: Final[int] = 10
MAX_FRAGMENTS_PER_QUERY_STRATEGY: Final[int] = 50
MAX_TOTAL_FRAGMENTS: Final[int] = 100
MAX_CONTEXT_QUERY_DOCUMENT_IDS: Final[int] = 50

MAX_POST_PROCESS_DOCUMENT_IDS: Final[int] = 10_000
MAX_POST_PROCESS_FRAGMENTS_DOCUMENT_IDS: Final[int] = 500
MAX_POST_PROCESS_SNAPSHOT_ERRORS: Final[int] = 1_000
MAX_JOB_ID_CHARS: Final[int] = 64
MAX_MESSAGE_CHARS: Final[int] = 500
MAX_ERROR_MESSAGE_CHARS: Final[int] = 500
MAX_POST_PROCESS_ERROR_MESSAGE_CHARS: Final[int] = 2_000

MAX_EMAIL_CHARS: Final[int] = 254
MAX_ROLE_CHARS: Final[int] = 100
MAX_PERMISSION_CHARS: Final[int] = 100
MAX_ROLES: Final[int] = 50
MAX_PERMISSIONS: Final[int] = 1_000

# ─── LLM provider payload ceilings ────────────────────────────────────────────

MAX_LLM_DOCUMENT_NAME_CHARS: Final[int] = 255
MAX_LLM_CLASSIFY_CONTENT_CHARS: Final[int] = 50_000
MAX_LLM_CONTEXTUALIZE_CONTENT_CHARS: Final[int] = 50_000
MAX_LLM_CONTEXTUALIZE_SUMMARY_CHARS: Final[int] = 2_000
MAX_LLM_CONTEXTUAL_PREFIX_CHARS: Final[int] = 2_000
MAX_LLM_EXTRACT_CONTENT_CHARS: Final[int] = 50_000
