from datetime import datetime
from typing import TYPE_CHECKING, Optional
import enum
import uuid

from sqlalchemy import String, Text, DateTime, Enum, ForeignKey
from sqlalchemy.dialects.postgresql import UUID, JSONB
from sqlalchemy.orm import Mapped, mapped_column, relationship
from sqlalchemy.sql import func

from app.domain.models.base import Base

if TYPE_CHECKING:
    from app.domain.models.message import Message


class ToolCallStatus(enum.Enum):
    """Status of a tool call execution."""
    pending = "pending"
    executing = "executing"
    completed = "completed"
    failed = "failed"


class ToolCall(Base):
    """
    Represents a function/tool call requested by the assistant.
    
    When the LLM requests a tool call, this record is created.
    The client executes the tool and submits the result back.
    """
    __tablename__ = "tool_call"

    # Primary key
    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4
    )

    # Foreign key
    message_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("message.id", ondelete="CASCADE"),
        nullable=False
    )

    # Tool call ID (generated by the LLM)
    tool_call_id: Mapped[str] = mapped_column(
        String(100),
        unique=True,
        nullable=False
    )

    # Tool information
    tool_type: Mapped[str] = mapped_column(
        String(50),
        default="function",
        nullable=False
    )
    function_name: Mapped[str] = mapped_column(String(255), nullable=False)
    function_args: Mapped[dict] = mapped_column(JSONB, nullable=False)

    # Execution result
    status: Mapped[ToolCallStatus] = mapped_column(
        Enum(ToolCallStatus),
        default=ToolCallStatus.pending,
        nullable=False
    )
    result: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    error_message: Mapped[Optional[str]] = mapped_column(Text, nullable=True)

    # Timing
    started_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True),
        nullable=True
    )
    completed_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True),
        nullable=True
    )

    # Audit fields
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False
    )

    # Relationships
    message: Mapped["Message"] = relationship(
        "Message",
        back_populates="tool_calls"
    )

    def __repr__(self) -> str:
        return f"<ToolCall(id={self.tool_call_id}, function={self.function_name})>"

    def mark_executing(self) -> None:
        """Mark the tool call as executing."""
        self.status = ToolCallStatus.executing
        self.started_at = datetime.utcnow()

    def mark_completed(self, result: str) -> None:
        """Mark the tool call as completed with a result."""
        self.status = ToolCallStatus.completed
        self.result = result
        self.completed_at = datetime.utcnow()

    def mark_failed(self, error_message: str) -> None:
        """Mark the tool call as failed with an error message."""
        self.status = ToolCallStatus.failed
        self.error_message = error_message
        self.completed_at = datetime.utcnow()


