import pytest

from core.authentication.authenticated_user import AuthenticatedUser
from core.authorization.permissions import (
    ADD_DOCUMENT_COLLECTION_DOCUMENT,
    ADD_USER_COMPARTMENT,
    CREATE_CLASSIFICATION_LEVEL,
    CREATE_COMPARTMENT,
    CREATE_DOCUMENT_COLLECTION,
    DELETE_CLASSIFICATION_LEVEL,
    DELETE_COMPARTMENT,
    DELETE_DOCUMENT_COLLECTION,
    DELETE_USER_CLEARANCE,
    GET_CLASSIFICATION_LEVEL,
    GET_COMPARTMENT,
    GET_DOCUMENT_COLLECTION,
    GET_USER_ACCESSIBLE_COLLECTIONS,
    GET_USER_AUTHORIZATION,
    LIST_CLASSIFICATION_LEVELS,
    LIST_COMPARTMENTS,
    LIST_DOCUMENT_COLLECTION_DOCUMENTS,
    LIST_DOCUMENT_COLLECTIONS,
    LIST_USER_COMPARTMENTS,
    REMOVE_DOCUMENT_COLLECTION_DOCUMENT,
    REMOVE_USER_COMPARTMENT,
    SET_USER_CLEARANCE,
    UPDATE_CLASSIFICATION_LEVEL,
    UPDATE_COMPARTMENT,
    UPDATE_DOCUMENT_COLLECTION,
)

_ALL_PERMISSIONS = (
    LIST_DOCUMENT_COLLECTIONS,
    CREATE_DOCUMENT_COLLECTION,
    GET_DOCUMENT_COLLECTION,
    UPDATE_DOCUMENT_COLLECTION,
    DELETE_DOCUMENT_COLLECTION,
    LIST_DOCUMENT_COLLECTION_DOCUMENTS,
    ADD_DOCUMENT_COLLECTION_DOCUMENT,
    REMOVE_DOCUMENT_COLLECTION_DOCUMENT,
    LIST_CLASSIFICATION_LEVELS,
    CREATE_CLASSIFICATION_LEVEL,
    GET_CLASSIFICATION_LEVEL,
    UPDATE_CLASSIFICATION_LEVEL,
    DELETE_CLASSIFICATION_LEVEL,
    LIST_COMPARTMENTS,
    CREATE_COMPARTMENT,
    GET_COMPARTMENT,
    UPDATE_COMPARTMENT,
    DELETE_COMPARTMENT,
    GET_USER_AUTHORIZATION,
    SET_USER_CLEARANCE,
    DELETE_USER_CLEARANCE,
    LIST_USER_COMPARTMENTS,
    ADD_USER_COMPARTMENT,
    REMOVE_USER_COMPARTMENT,
    GET_USER_ACCESSIBLE_COLLECTIONS,
)


def make_user(id: int, **kwargs) -> AuthenticatedUser:
    return AuthenticatedUser(
        id=id,
        email=f"user{id}@test.com",
        username=f"user{id}",
        permissions=_ALL_PERMISSIONS,
        **kwargs,
    )


@pytest.fixture
def admin():
    return make_user(id=1000)


@pytest.fixture
def other_user():
    return make_user(id=1001)
