GET http://localhost:8000/api/document-query/document/29
Accept: application/json
Content-Type: application/json
Authorization: Bearer user_token_123


###


GET http://localhost:8000/api/document-query/documents
Accept: application/json
Content-Type: application/json
Authorization: Bearer user_token_123


###


GET http://localhost:8000/api/document-query/documents?page=0&size=20&name=&category=
Accept: application/json
Content-Type: application/json
Authorization: Bearer user_token_123


###
