@dpsBase = http://localhost:8000/api/v1
@authToken = user_token_123

### Documento por id
GET {{dpsBase}}/document-query/document/29
Accept: application/json
Authorization: Bearer {{authToken}}


### Listar documentos
GET {{dpsBase}}/document-query/documents
Accept: application/json
Authorization: Bearer {{authToken}}


### Paginación y filtros
GET {{dpsBase}}/document-query/documents?page=1&size=20&name=&category=
Accept: application/json
Authorization: Bearer {{authToken}}


### Documentos por chat
GET {{dpsBase}}/document-query/documents/chat/1
Accept: application/json
Authorization: Bearer {{authToken}}
