@dpsBase = http://localhost:8000/api/v1
@authToken = user_token_123

### Descarga de documento
GET {{dpsBase}}/document-download/document/29/download
Accept: application/octet-stream
Authorization: Bearer {{authToken}}
