@dpsBase = http://localhost:8000/api/v1
@authToken = user_token_123

### Iniciar post-proceso de documentos
POST {{dpsBase}}/post-process-document/start
Accept: application/json
Authorization: Bearer {{authToken}}


### Encolar documentos concretos
POST {{dpsBase}}/post-process-document/documents
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "document_ids": [1, 2]
}


### Estado
GET {{dpsBase}}/post-process-document/status
Accept: application/json
Authorization: Bearer {{authToken}}


### Detener
DELETE {{dpsBase}}/post-process-document/stop
Accept: application/json
Authorization: Bearer {{authToken}}
