POST http://localhost:8000/api/v1/post-process-document/start
Accept: application/json
Content-Type: application/json
Authorization: Bearer user_token_123


###


POST http://localhost:8000/api/v1/post-process-document/documents
Accept: application/json
Content-Type: application/json
Authorization: Bearer user_token_123

{
  "document_ids": [1, 2]
}


###


GET http://localhost:8000/api/v1/post-process-document/status
Accept: application/json
Content-Type: application/json
Authorization: Bearer user_token_123


###


DELETE http://localhost:8000/api/v1/post-process-document/stop
Accept: application/json
Content-Type: application/json
Authorization: Bearer user_token_123


###
