# Chats
MANAGE_CHATS = "MANAGE_CHATS"
LIST_CHATS = "LIST_CHATS"
LIST_MY_CHATS = "LIST_MY_CHATS"
LIST_ARCHIVED_CHATS = "LIST_ARCHIVED_CHATS"
CREATE_CHAT = "CREATE_CHAT"
GET_CHAT = "GET_CHAT"
UPDATE_CHAT = "UPDATE_CHAT"
DELETE_CHAT = "DELETE_CHAT"
PIN_CHAT = "PIN_CHAT"
ARCHIVE_CHAT = "ARCHIVE_CHAT"
UNARCHIVE_CHAT = "UNARCHIVE_CHAT"
LOCK_CHAT = "LOCK_CHAT"
MUTE_CHAT = "MUTE_CHAT"

# Share Links
LIST_SHARE_LINKS = "LIST_SHARE_LINKS"
CREATE_SHARE_LINK = "CREATE_SHARE_LINK"
DELETE_SHARE_LINK = "DELETE_SHARE_LINK"

# Members
LIST_MEMBERS = "LIST_MEMBERS"
LIST_MY_MEMBERSHIPS = "LIST_MY_MEMBERSHIPS"
ADD_MEMBER = "ADD_MEMBER"
UPDATE_MEMBER = "UPDATE_MEMBER"
REMOVE_MEMBER = "REMOVE_MEMBER"
LEAVE_CHAT = "LEAVE_CHAT"
UPDATE_MEMBER_ROLE = "UPDATE_MEMBER_ROLE"
MANAGE_MEMBERS = "MANAGE_MEMBERS"

# Messages
LIST_MESSAGES = "LIST_MESSAGES"
SEND_MESSAGE = "SEND_MESSAGE"
DELETE_MESSAGE = "DELETE_MESSAGE"
CLEAR_CHAT_HISTORY = "CLEAR_CHAT_HISTORY"
MARK_CHAT_AS_READ = "MARK_CHAT_AS_READ"
REGENERATE_AI_RESPONSE = "REGENERATE_AI_RESPONSE"

# Bookmarks
LIST_BOOKMARKS = "LIST_BOOKMARKS"
BOOKMARK_MESSAGE = "BOOKMARK_MESSAGE"

# Pinned Messages
LIST_PINNED_MESSAGES = "LIST_PINNED_MESSAGES"
PIN_MESSAGE = "PIN_MESSAGE"

# Feedback
SET_MESSAGE_FEEDBACK = "SET_MESSAGE_FEEDBACK"
VIEW_FEEDBACK_ANALYTICS = "VIEW_FEEDBACK_ANALYTICS"

# Threads
LIST_THREAD_REPLIES = "LIST_THREAD_REPLIES"
ADD_THREAD_REPLY = "ADD_THREAD_REPLY"

# Export
EXPORT_CHAT = "EXPORT_CHAT"

# LLM
LLM_REPORT_GENERATE = "LLM_REPORT_GENERATE"
LLM_CHECKLIST_GENERATE = "LLM_CHECKLIST_GENERATE"

# Reports
LIST_REPORTS = "LIST_REPORTS"
CREATE_REPORT = "CREATE_REPORT"
GET_REPORT = "GET_REPORT"
UPDATE_REPORT = "UPDATE_REPORT"
DELETE_REPORT = "DELETE_REPORT"
EXPORT_REPORT = "EXPORT_REPORT"
MANAGE_REPORTS = "MANAGE_REPORTS"
MANAGE_EXPORT_REPORT = "MANAGE_EXPORT_REPORT"

# Checklists
LIST_CHECKLISTS = "LIST_CHECKLISTS"
CREATE_CHECKLIST = "CREATE_CHECKLIST"
GET_CHECKLIST = "GET_CHECKLIST"
UPDATE_CHECKLIST = "UPDATE_CHECKLIST"
DELETE_CHECKLIST = "DELETE_CHECKLIST"
EXPORT_CHECKLIST = "EXPORT_CHECKLIST"
MANAGE_CHECKLISTS = "MANAGE_CHECKLISTS"
MANAGE_EXPORT_CHECKLIST = "MANAGE_EXPORT_CHECKLIST"

# Assistants (user)
LIST_ASSISTANTS = "LIST_ASSISTANTS"
GET_ASSISTANT = "GET_ASSISTANT"
USE_ASSISTANT = "USE_ASSISTANT"

# Assistants (admin)
CREATE_ASSISTANT = "CREATE_ASSISTANT"
UPDATE_ASSISTANT = "UPDATE_ASSISTANT"
DELETE_ASSISTANT = "DELETE_ASSISTANT"
MANAGE_ASSISTANTS = "MANAGE_ASSISTANTS"
