LIST_CHATS = "LIST_CHATS"
CREATE_CHAT = "CREATE_CHAT"
GET_CHAT = "GET_CHAT"
UPDATE_CHAT = "UPDATE_CHAT"
DELETE_CHAT = "DELETE_CHAT"

LIST_MESSAGES = "LIST_MESSAGES"
SEND_MESSAGE = "SEND_MESSAGE"

LIST_MEMBERS = "LIST_MEMBERS"
ADD_MEMBER = "ADD_MEMBER"
REMOVE_MEMBER = "REMOVE_MEMBER"
UPDATE_MEMBER = "UPDATE_MEMBER"
