# Chats
MANAGE_CHATS = "MANAGE_CHATS"
LIST_CHATS = "LIST_CHATS"
LIST_MY_CHATS = "LIST_MY_CHATS"
LIST_ARCHIVED_CHATS = "LIST_ARCHIVED_CHATS"
CREATE_CHAT = "CREATE_CHAT"
GET_CHAT = "GET_CHAT"
UPDATE_CHAT = "UPDATE_CHAT"
DELETE_CHAT = "DELETE_CHAT"
PIN_CHAT = "PIN_CHAT"
ARCHIVE_CHAT = "ARCHIVE_CHAT"
UNARCHIVE_CHAT = "UNARCHIVE_CHAT"
LOCK_CHAT = "LOCK_CHAT"

# Share Links
LIST_SHARE_LINKS = "LIST_SHARE_LINKS"
CREATE_SHARE_LINK = "CREATE_SHARE_LINK"
DELETE_SHARE_LINK = "DELETE_SHARE_LINK"

# Members
LIST_MEMBERS = "LIST_MEMBERS"
LIST_MY_MEMBERSHIPS = "LIST_MY_MEMBERSHIPS"
ADD_MEMBER = "ADD_MEMBER"
UPDATE_MEMBER = "UPDATE_MEMBER"
REMOVE_MEMBER = "REMOVE_MEMBER"
LEAVE_CHAT = "LEAVE_CHAT"
UPDATE_MEMBER_ROLE = "UPDATE_MEMBER_ROLE"
MANAGE_MEMBERS = "MANAGE_MEMBERS"

# Messages
LIST_MESSAGES = "LIST_MESSAGES"
GET_MESSAGE = "GET_MESSAGE"
SEND_MESSAGE = "SEND_MESSAGE"
DELETE_MESSAGE = "DELETE_MESSAGE"
EXPORT_MESSAGE = "EXPORT_MESSAGE"
MANAGE_MESSAGES = "MANAGE_MESSAGES"
MANAGE_EXPORT_MESSAGE = "MANAGE_EXPORT_MESSAGE"
CLEAR_CHAT_HISTORY = "CLEAR_CHAT_HISTORY"
MARK_CHAT_AS_READ = "MARK_CHAT_AS_READ"

# Bookmarks
LIST_BOOKMARKS = "LIST_BOOKMARKS"
BOOKMARK_MESSAGE = "BOOKMARK_MESSAGE"

# Pinned Messages
LIST_PINNED_MESSAGES = "LIST_PINNED_MESSAGES"
PIN_MESSAGE = "PIN_MESSAGE"

# Feedback
SET_MESSAGE_FEEDBACK = "SET_MESSAGE_FEEDBACK"
VIEW_FEEDBACK_ANALYTICS = "VIEW_FEEDBACK_ANALYTICS"

# Threads
LIST_THREAD_REPLIES = "LIST_THREAD_REPLIES"
ADD_THREAD_REPLY = "ADD_THREAD_REPLY"
EDIT_THREAD_REPLY = "EDIT_THREAD_REPLY"
DELETE_THREAD_REPLY = "DELETE_THREAD_REPLY"

# Export
EXPORT_CHAT = "EXPORT_CHAT"

# LLM
LLM_REPORT_GENERATE = "LLM_REPORT_GENERATE"
LLM_CHECKLIST_GENERATE = "LLM_CHECKLIST_GENERATE"
LLM_TIMELINE_GENERATE = "LLM_TIMELINE_GENERATE"
LLM_QUIZ_GENERATE = "LLM_QUIZ_GENERATE"
LLM_LESSONS_LEARNED_GENERATE = "LLM_LESSONS_LEARNED_GENERATE"
LLM_DECISION_BRIEF_GENERATE = "LLM_DECISION_BRIEF_GENERATE"
LLM_DOCUMENT_SUMMARY_GENERATE = "LLM_DOCUMENT_SUMMARY_GENERATE"
LLM_DOCUMENT_ACTION_GENERATE = "LLM_DOCUMENT_ACTION_GENERATE"

# Reports
LIST_REPORTS = "LIST_REPORTS"
GET_REPORT = "GET_REPORT"
DELETE_REPORT = "DELETE_REPORT"
EXPORT_REPORT = "EXPORT_REPORT"
MANAGE_REPORTS = "MANAGE_REPORTS"
MANAGE_EXPORT_REPORT = "MANAGE_EXPORT_REPORT"

# Checklists
LIST_CHECKLISTS = "LIST_CHECKLISTS"
GET_CHECKLIST = "GET_CHECKLIST"
UPDATE_CHECKLIST = "UPDATE_CHECKLIST"
DELETE_CHECKLIST = "DELETE_CHECKLIST"
EXPORT_CHECKLIST = "EXPORT_CHECKLIST"
MANAGE_CHECKLISTS = "MANAGE_CHECKLISTS"
MANAGE_EXPORT_CHECKLIST = "MANAGE_EXPORT_CHECKLIST"

# Timelines
LIST_TIMELINES = "LIST_TIMELINES"
GET_TIMELINE = "GET_TIMELINE"
DELETE_TIMELINE = "DELETE_TIMELINE"
EXPORT_TIMELINE = "EXPORT_TIMELINE"
MANAGE_TIMELINES = "MANAGE_TIMELINES"
MANAGE_EXPORT_TIMELINE = "MANAGE_EXPORT_TIMELINE"

# Quizzes
LIST_QUIZZES = "LIST_QUIZZES"
GET_QUIZ = "GET_QUIZ"
UPDATE_QUIZ = "UPDATE_QUIZ"
DELETE_QUIZ = "DELETE_QUIZ"
EXPORT_QUIZ = "EXPORT_QUIZ"
MANAGE_QUIZZES = "MANAGE_QUIZZES"
MANAGE_EXPORT_QUIZ = "MANAGE_EXPORT_QUIZ"

# Lessons Learned
LIST_LESSONS_LEARNED = "LIST_LESSONS_LEARNED"
GET_LESSONS_LEARNED = "GET_LESSONS_LEARNED"
DELETE_LESSONS_LEARNED = "DELETE_LESSONS_LEARNED"
EXPORT_LESSONS_LEARNED = "EXPORT_LESSONS_LEARNED"
MANAGE_LESSONS_LEARNED = "MANAGE_LESSONS_LEARNED"
MANAGE_EXPORT_LESSONS_LEARNED = "MANAGE_EXPORT_LESSONS_LEARNED"

# Decision Briefs
LIST_DECISION_BRIEFS = "LIST_DECISION_BRIEFS"
GET_DECISION_BRIEF = "GET_DECISION_BRIEF"
DELETE_DECISION_BRIEF = "DELETE_DECISION_BRIEF"
EXPORT_DECISION_BRIEF = "EXPORT_DECISION_BRIEF"
MANAGE_DECISION_BRIEFS = "MANAGE_DECISION_BRIEFS"
MANAGE_EXPORT_DECISION_BRIEF = "MANAGE_EXPORT_DECISION_BRIEF"

# Document Summaries
LIST_DOCUMENT_SUMMARIES = "LIST_DOCUMENT_SUMMARIES"
GET_DOCUMENT_SUMMARY = "GET_DOCUMENT_SUMMARY"
DELETE_DOCUMENT_SUMMARY = "DELETE_DOCUMENT_SUMMARY"
EXPORT_DOCUMENT_SUMMARY = "EXPORT_DOCUMENT_SUMMARY"
MANAGE_DOCUMENT_SUMMARIES = "MANAGE_DOCUMENT_SUMMARIES"
MANAGE_EXPORT_DOCUMENT_SUMMARY = "MANAGE_EXPORT_DOCUMENT_SUMMARY"

# Document Actions
LIST_DOCUMENT_ACTIONS = "LIST_DOCUMENT_ACTIONS"
GET_DOCUMENT_ACTION = "GET_DOCUMENT_ACTION"
DELETE_DOCUMENT_ACTION = "DELETE_DOCUMENT_ACTION"
EXPORT_DOCUMENT_ACTION = "EXPORT_DOCUMENT_ACTION"
MANAGE_DOCUMENT_ACTIONS = "MANAGE_DOCUMENT_ACTIONS"
MANAGE_EXPORT_DOCUMENT_ACTION = "MANAGE_EXPORT_DOCUMENT_ACTION"

# Artifacts
LIST_ARTIFACTS = "LIST_ARTIFACTS"
GET_ARTIFACT = "GET_ARTIFACT"
DELETE_ARTIFACT = "DELETE_ARTIFACT"
MANAGE_ARTIFACTS = "MANAGE_ARTIFACTS"
MANAGE_CHAT_ARTIFACTS = "MANAGE_CHAT_ARTIFACTS"

# Assistants (user)
LIST_ASSISTANTS = "LIST_ASSISTANTS"
GET_ASSISTANT = "GET_ASSISTANT"
USE_ASSISTANT = "USE_ASSISTANT"

# Assistants (admin)
CREATE_ASSISTANT = "CREATE_ASSISTANT"
UPDATE_ASSISTANT = "UPDATE_ASSISTANT"
DELETE_ASSISTANT = "DELETE_ASSISTANT"
MANAGE_ASSISTANTS = "MANAGE_ASSISTANTS"
