GET http://localhost:8000/api/document-query/document/1
Accept: application/json
Content-Type: application/json
Authorization: Bearer user_token_123


###


GET http://localhost:8000/api/document-query/documents
Accept: application/json
Content-Type: application/json
Authorization: Bearer user_token_123


###
