POST http://localhost:8000/api/document-creation
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Authorization: Bearer user_token_123

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="chat_id"

12345
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="raw_document"; filename="Avión_de_Caza_Multirrol_F-X_“Halcón_Boreal”_digital_pdf.pdf"
Content-Type: application/pdf

< ./test_documents/Avión_de_Caza_Multirrol_F-X_“Halcón_Boreal”_digital_pdf.pdf
------WebKitFormBoundary7MA4YWxkTrZu0gW--


###


POST http://localhost:8000/api/document-creation
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Authorization: Bearer user_token_123

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="chat_id"

12345
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="raw_document"; filename="El_perro_que_cazó_a_la_ballena_digital_pdf.pdf"
Content-Type: application/pdf

< ./test_documents/El_perro_que_cazó_a_la_ballena_digital_pdf.pdf
------WebKitFormBoundary7MA4YWxkTrZu0gW--


###


POST http://localhost:8000/api/document-creation
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Authorization: Bearer user_token_123

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="chat_id"

12345
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="raw_document"; filename="El_niño_que_no_sabía_envejecer_digital_docx.docx"
Content-Type: application/vnd.openxmlformats-officedocument.wordprocessingml.document

< ./test_documents/El_niño_que_no_sabía_envejecer_digital_docx.docx
------WebKitFormBoundary7MA4YWxkTrZu0gW--


###


POST http://localhost:8000/api/document-creation
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Authorization: Bearer user_token_123

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="chat_id"

12345
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="raw_document"; filename="Rifle_Automático_de_Asalto_AR-9_“Centinela”_digital_docx.docx"
Content-Type: application/vnd.openxmlformats-officedocument.wordprocessingml.document

< ./test_documents/Rifle_Automático_de_Asalto_AR-9_“Centinela”_digital_docx.docx
------WebKitFormBoundary7MA4YWxkTrZu0gW--


###


POST http://localhost:8001/api/document-creation
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Authorization: Bearer user_token_123

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="chat_id"

12345
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="raw_document"; filename="El_Big_Bang__el_origen_del_tiempo,_el_espacio_y_todo_lo_que_existe_scanned_docx.docx"
Content-Type: application/vnd.openxmlformats-officedocument.wordprocessingml.document

< ./test_documents/El_Big_Bang__el_origen_del_tiempo,_el_espacio_y_todo_lo_que_existe_scanned_docx.docx
------WebKitFormBoundary7MA4YWxkTrZu0gW--


###


POST http://localhost:8001/api/document-creation
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Authorization: Bearer user_token_123

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="chat_id"

12345
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="raw_document"; filename="Fuerzas_Conjuntas_de_Asterión_scanned_pdf.pdf"
Content-Type: application/pdf

< ./test_documents/Fuerzas_Conjuntas_de_Asterión_scanned_pdf.pdf
------WebKitFormBoundary7MA4YWxkTrZu0gW--


###


POST http://localhost:8000/api/document-creation
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Authorization: Bearer user_token_123

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="chat_id"

12345
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="raw_document"; filename="Arte_y_Cultura_Capitulo_I_digital_pdf.pdf"
Content-Type: application/pdf

< ./test_documents/Arte_y_Cultura_Capitulo_I_digital_pdf.pdf
------WebKitFormBoundary7MA4YWxkTrZu0gW--


###


POST http://localhost:8000/api/document-creation
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Authorization: Bearer user_token_123

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="chat_id"

12345
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="raw_document"; filename="Ciencia_y_Tecnologia_Capitulo_I_digital_docx.docx"
Content-Type: application/pdf

< ./test_documents/Ciencia_y_Tecnologia_Capitulo_I_digital_docx.docx
------WebKitFormBoundary7MA4YWxkTrZu0gW--


###


POST http://localhost:8000/api/document-creation
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Authorization: Bearer user_token_123

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="chat_id"

12345
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="raw_document"; filename="Historia_Universal_Capitulo_I_digital_docx.docx"
Content-Type: application/pdf

< ./test_documents/Historia_Universal_Capitulo_I_digital_docx.docx
------WebKitFormBoundary7MA4YWxkTrZu0gW--


###


POST http://localhost:8000/api/document-creation
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Authorization: Bearer user_token_123

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="chat_id"

12345
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="raw_document"; filename="Religiones_del_Mundo_digital_pdf.docx.pdf"
Content-Type: application/pdf

< ./test_documents/Religiones_del_Mundo_digital_pdf.docx.pdf
------WebKitFormBoundary7MA4YWxkTrZu0gW--


###


GET http://localhost:8001/api/document-creation/document/12
Accept: application/json
Content-Type: application/json
Authorization: Bearer user_token_123


###
