scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'aura-auth-service'
    metrics_path: '/metrics'
    scrape_interval: 10s
    static_configs:
      - targets: ['aura-auth-service:8000']

  - job_name: 'aura-chat-service'
    metrics_path: '/metrics'
    scrape_interval: 10s
    static_configs:
      - targets: ['aura-chat-service:8000']

  - job_name: 'aura-document-processing-service'
    metrics_path: '/metrics'
    scrape_interval: 10s
    static_configs:
      - targets: ['aura-document-processing-service:8000']

  - job_name: 'aura-llm-service'
    metrics_path: '/metrics'
    scrape_interval: 10s
    static_configs:
      - targets: ['aura-llm-service:8000']

  - job_name: 'aura-document-collection-service'
    metrics_path: '/metrics'
    scrape_interval: 10s
    static_configs:
      - targets: ['aura-document-collection-service:8000']

  - job_name: 'aura-notification-service'
    metrics_path: '/metrics'
    scrape_interval: 10s
    static_configs:
      - targets: ['aura-notification-service:8000']
