# Generated by Django 6.0.4 on 2026-04-12 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_by', models.BigIntegerField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('message', models.TextField()),
                ('sender_type', models.CharField(choices=[('system', 'System'), ('user', 'User')], max_length=10)),
                ('created_by', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chat')),
            ],
            options={
                'db_table': 'chat_message',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['chat'], name='idx_chat_message_chat_id')],
            },
        ),
    ]
