"""Chat admin — migrated to a custom view pattern.

The previous `ChatAdmin(admin.ModelAdmin)` registered here has been removed.
The list view (search, pagination), detail view (messages, share links,
members) and the share-link revoke action now live in
``accounts/admin_parts/chat_management_admin.py`` as plain Django views
backed by ``accounts.services.chat_client``, following the same
ModelAdmin-free pattern as ``accounts/admin_parts/mac_admin.py``.

Reasons for the move (see the migration analysis delivered alongside this
change for the full reasoning):
  - Django's `ChangeList`/`Paginator`/`get_object` machinery requires real
    QuerySet semantics that a remote, paginated REST API can't satisfy
    without re-implementing significant parts of that machinery.
  - The list view now calls aura-chat-service's `GET /api/v1/chats/manage/`
    directly, with a fallback to the local `aura_db` `Chat` mirror (this
    module's models, still defined in chat/models.py) if the service is
    unavailable.

`chat/models.py` (Chat, ChatMessage, ChatMembership) is intentionally kept
— the new list view's fallback path queries `Chat` directly, and removing
the models would also remove that safety net.

URL names that used to be auto-generated by the ModelAdmin registration
(`chat_chat_changelist`, `chat_chat_change`) no longer exist; any code
referencing them must use `chat_management_list` / `chat_management_detail`
instead (see accounts/admin_parts/site_config.py).
"""
