POST http://localhost:8001/api/document-question
Accept: application/json
Content-Type: application/json
Authorization: Bearer user_token_123

{
  "messages": [
    {
      "role": "human",
      "content": "¿Puede una aeronave aterrizar fuera de un aeródromo habilitado? ¿En qué casos?"
    }
  ]
}


###


POST http://localhost:8001/api/document-question
Accept: application/json
Content-Type: application/json
Authorization: Bearer user_token_123

{
  "messages": [
    {
      "role": "human",
      "content": "¿Qué es el Programa Nacional de Seguridad de la Aviación Civil (PNSAC)?"
    }
  ]
}


###


POST http://localhost:8001/api/document-question
Accept: application/json
Content-Type: application/json
Authorization: Bearer user_token_123

{
  "messages": [
    {
      "role": "human",
      "content": "¿Qué se entiende por verificación de antecedentes en el ámbito AVSEC?"
    }
  ]
}

