@llmBase = http://localhost:8001/api/v1
@authToken = user_token_123

POST {{llmBase}}/document-classify
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "document_name": "ejemplo.pdf",
  "content": "Texto o extracto del documento a clasificar."
}


###
