@llmBase = http://localhost:8001/api/v1
@authToken = user_token_123

POST {{llmBase}}/fragment-enrich
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "content": "Fragmento de texto a enriquecer con contexto o metadatos."
}


###
