[pytest]
DJANGO_SETTINGS_MODULE = aura_chat_service.settings.test
python_files = test/test_*.py test/integration/test_*.py test/unit/chat/test_*.py test/unit/checklist/test_*.py test/unit/report/test_*.py test/unit/assistant/test_*.py test/unit/shared_link/test_*.py test/unit/membership/test_*.py test/unit/message/test_*.py test/unit/artifact/test_*.py
python_classes = Test*
python_functions = test_*
asyncio_mode = strict
