[pytest]
DJANGO_SETTINGS_MODULE = aura_chat_service.settings.test
python_files = test/test_*.py test/integration/test_*.py test/checklist/test_*.py test/report/test_*.py test/assistant/test_*.py test/shared_link/test_*.py test/membership/test_*.py test/message/test_*.py
python_classes = Test*
python_functions = test_*
asyncio_mode = strict
