# Generated by Django 5.1.6 on 2026-02-10 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.RunSQL(
            """
            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1 FROM pg_type WHERE typname = 'user_status'
                ) THEN
                    CREATE TYPE user_status AS ENUM ('active', 'inactive');
                END IF;
            END
            $$;
            """,
            "DROP TYPE IF EXISTS user_status;",
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "username",
                    models.CharField(
                        max_length=255,
                        unique=True,
                        verbose_name="Usuario",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=255,
                        unique=True,
                        verbose_name="Correo",
                    ),
                ),
                (
                    "password",
                    models.CharField(
                        help_text="Hashed password",
                        max_length=255,
                        verbose_name="Contraseña",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Activo"), ("inactive", "Inactivo")],
                        max_length=8,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Último login",
                    ),
                ),
                ("account_non_expired", models.BooleanField(default=True)),
                ("account_non_locked", models.BooleanField(default=True)),
                ("failed_login_attempts", models.IntegerField(blank=True, null=True)),
                ("lockout_until", models.DateTimeField(blank=True, null=True)),
                ("credentials_non_expired", models.BooleanField(default=True)),
                (
                    "last_password_change",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Ultimo cambio de contrasena",
                    ),
                ),
                ("refresh_token", models.UUIDField(blank=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Fecha creado"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Fecha actualizado"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Fecha eliminado",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        db_column="created_by",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_users",
                        verbose_name="Creado por",
                        to="accounts.user",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="updated_by",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="updated_users",
                        verbose_name="Actualizado por",
                        to="accounts.user",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="deleted_by",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deleted_users",
                        verbose_name="Eliminado por",
                        to="accounts.user",
                    ),
                ),
            ],
            options={
                "db_table": "auth_user",
                "verbose_name": "Usuario",
                "verbose_name_plural": "Usuarios",
            },
        ),
        migrations.RunSQL(
            "ALTER TABLE auth_user ALTER COLUMN status TYPE user_status USING status::text::user_status;",
            "ALTER TABLE auth_user ALTER COLUMN status TYPE varchar(8) USING status::text;",
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255, verbose_name="Nombre")),
                (
                    "description",
                    models.CharField(max_length=255, verbose_name="Descripción"),
                ),
            ],
            options={
                "db_table": "role",
                "verbose_name": "Rol",
                "verbose_name_plural": "Roles",
            },
        ),
        migrations.CreateModel(
            name="Permission",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255, verbose_name="Nombre")),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Descripción",
                    ),
                ),
            ],
            options={
                "db_table": "permission",
                "verbose_name": "Permiso",
                "verbose_name_plural": "Permisos",
            },
        ),
        migrations.CreateModel(
            name="UserRole",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateField(auto_now_add=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        db_column="created_by",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_user_roles",
                        to="accounts.user",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="deleted_by",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deleted_user_roles",
                        to="accounts.user",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        db_column="role_id",
                        help_text="Role reference",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="user_assignments",
                        verbose_name="Rol",
                        to="accounts.role",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="auth_user_id",
                        help_text="User reference",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="user_roles",
                        verbose_name="Usuario",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "auth_user_in_role",
                "verbose_name": "Rol de Usuario",
                "verbose_name_plural": "Roles de Usuario",
            },
        ),
        migrations.CreateModel(
            name="PermissionInRole",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "permission",
                    models.ForeignKey(
                        db_column="permission_id",
                        help_text="Permission reference",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="role_links",
                        verbose_name="Permiso",
                        to="accounts.permission",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        db_column="role_id",
                        help_text="Role reference",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="permission_links",
                        verbose_name="Rol",
                        to="accounts.role",
                    ),
                ),
            ],
            options={
                "db_table": "permission_in_role",
                "verbose_name": "Permiso de Rol",
                "verbose_name_plural": "Permisos de Rol",
            },
        ),
    ]
