# Generated by Django 5.1.6 on 2026-02-04 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="permission",
            options={"verbose_name": "Permiso", "verbose_name_plural": "Permisos"},
        ),
        migrations.AlterModelOptions(
            name="role",
            options={"verbose_name": "Rol", "verbose_name_plural": "Roles"},
        ),
        migrations.AlterModelOptions(
            name="rolepermission",
            options={
                "verbose_name": "Permiso de Rol",
                "verbose_name_plural": "Permisos de Rol",
            },
        ),
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "Usuario", "verbose_name_plural": "Usuarios"},
        ),
        migrations.AlterModelOptions(
            name="userrole",
            options={
                "verbose_name": "Rol de Usuario",
                "verbose_name_plural": "Roles de Usuario",
            },
        ),
    ]
