# Generated by Django 5.1.6 on 2026-02-10 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_permission_options_alter_role_options_and_more"),
    ]

    operations = []
