# Generated by Django 5.1.6 on 2026-02-04 20:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_permission_options_alter_role_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="permission",
            name="code",
            field=models.CharField(
                db_index=True,
                help_text="Unique permission code (e.g., 'user.create', 'role.delete')",
                max_length=100,
                unique=True,
                verbose_name="Código",
            ),
        ),
        migrations.AlterField(
            model_name="permission",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Creation timestamp",
                verbose_name="Creado el",
            ),
        ),
        migrations.AlterField(
            model_name="permission",
            name="created_by",
            field=models.CharField(
                blank=True,
                help_text="Username who created this record",
                max_length=255,
                null=True,
                verbose_name="Creado por",
            ),
        ),
        migrations.AlterField(
            model_name="permission",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Soft delete timestamp (null = active)",
                null=True,
                verbose_name="Eliminado el",
            ),
        ),
        migrations.AlterField(
            model_name="permission",
            name="deleted_by",
            field=models.CharField(
                blank=True,
                help_text="Username who deleted this record",
                max_length=255,
                null=True,
                verbose_name="Eliminado por",
            ),
        ),
        migrations.AlterField(
            model_name="permission",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Permission description",
                verbose_name="Descripción",
            ),
        ),
        migrations.AlterField(
            model_name="permission",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Last update timestamp",
                verbose_name="Actualizado el",
            ),
        ),
        migrations.AlterField(
            model_name="permission",
            name="updated_by",
            field=models.CharField(
                blank=True,
                help_text="Username who last updated this record",
                max_length=255,
                null=True,
                verbose_name="Actualizado por",
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Creation timestamp",
                verbose_name="Creado el",
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="created_by",
            field=models.CharField(
                blank=True,
                help_text="Username who created this record",
                max_length=255,
                null=True,
                verbose_name="Creado por",
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Soft delete timestamp (null = active)",
                null=True,
                verbose_name="Eliminado el",
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="deleted_by",
            field=models.CharField(
                blank=True,
                help_text="Username who deleted this record",
                max_length=255,
                null=True,
                verbose_name="Eliminado por",
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Role description and purpose",
                verbose_name="Descripción",
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="name",
            field=models.CharField(
                db_index=True,
                help_text="Unique role name (e.g., SUPER_ADMIN, USER)",
                max_length=100,
                unique=True,
                verbose_name="Nombre",
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Last update timestamp",
                verbose_name="Actualizado el",
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="updated_by",
            field=models.CharField(
                blank=True,
                help_text="Username who last updated this record",
                max_length=255,
                null=True,
                verbose_name="Actualizado por",
            ),
        ),
        migrations.AlterField(
            model_name="rolepermission",
            name="granted_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="When this permission was granted",
                verbose_name="Concedido el",
            ),
        ),
        migrations.AlterField(
            model_name="rolepermission",
            name="granted_by",
            field=models.CharField(
                blank=True,
                help_text="Username who granted this permission",
                max_length=255,
                null=True,
                verbose_name="Concedido por",
            ),
        ),
        migrations.AlterField(
            model_name="rolepermission",
            name="permission",
            field=models.ForeignKey(
                help_text="Permission reference",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="permission_roles",
                to="accounts.permission",
                verbose_name="Permiso",
            ),
        ),
        migrations.AlterField(
            model_name="rolepermission",
            name="role",
            field=models.ForeignKey(
                help_text="Role reference",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="role_permissions",
                to="accounts.role",
                verbose_name="Rol",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Creation timestamp",
                verbose_name="Creado el",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="created_by",
            field=models.CharField(
                blank=True,
                help_text="Username who created this record",
                max_length=255,
                null=True,
                verbose_name="Creado por",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Soft delete timestamp (null = active)",
                null=True,
                verbose_name="Eliminado el",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="deleted_by",
            field=models.CharField(
                blank=True,
                help_text="Username who deleted this record",
                max_length=255,
                null=True,
                verbose_name="Eliminado por",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                db_index=True,
                help_text="Unique email address",
                max_length=254,
                unique=True,
                verbose_name="Correo electrónico",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Whether this user can login",
                verbose_name="Activo",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(
                default=False,
                help_text="Whether user can access admin panel",
                verbose_name="Es staff",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_superuser",
            field=models.BooleanField(
                default=False,
                help_text="Whether user has all permissions",
                verbose_name="Es superusuario",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_login",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Último login"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(
                help_text="Hashed password", max_length=255, verbose_name="Contraseña"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Last update timestamp",
                verbose_name="Actualizado el",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="updated_by",
            field=models.CharField(
                blank=True,
                help_text="Username who last updated this record",
                max_length=255,
                null=True,
                verbose_name="Actualizado por",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                db_index=True,
                help_text="Unique username for login",
                max_length=150,
                unique=True,
                verbose_name="Nombre de usuario",
            ),
        ),
        migrations.AlterField(
            model_name="userrole",
            name="assigned_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="When this role was assigned",
                verbose_name="Asignado el",
            ),
        ),
        migrations.AlterField(
            model_name="userrole",
            name="assigned_by",
            field=models.CharField(
                blank=True,
                help_text="Username who assigned this role",
                max_length=255,
                null=True,
                verbose_name="Asignado por",
            ),
        ),
        migrations.AlterField(
            model_name="userrole",
            name="role",
            field=models.ForeignKey(
                help_text="Role reference",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_assignments",
                to="accounts.role",
                verbose_name="Rol",
            ),
        ),
        migrations.AlterField(
            model_name="userrole",
            name="user",
            field=models.ForeignKey(
                help_text="User reference",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_roles",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuario",
            ),
        ),
    ]
