# Generated by Django 5.1.6 on 2026-02-10 00:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_permission_code_alter_permission_created_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RefreshToken",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Creation timestamp",
                        verbose_name="Creado",
                    ),
                ),
                (
                    "created_by",
                    models.CharField(
                        blank=True,
                        help_text="Username who created this record",
                        max_length=255,
                        null=True,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Last update timestamp",
                        verbose_name="Actualizado el",
                    ),
                ),
                (
                    "updated_by",
                    models.CharField(
                        blank=True,
                        help_text="Username who last updated this record",
                        max_length=255,
                        null=True,
                        verbose_name="Actualizado por",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Soft delete timestamp (null = active)",
                        null=True,
                        verbose_name="Eliminado el",
                    ),
                ),
                (
                    "deleted_by",
                    models.CharField(
                        blank=True,
                        help_text="Username who deleted this record",
                        max_length=255,
                        null=True,
                        verbose_name="Eliminado por",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        db_index=True,
                        help_text="Unique refresh token value (UUID)",
                        max_length=255,
                        unique=True,
                        verbose_name="Token",
                    ),
                ),
                (
                    "is_revoked",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether this token has been revoked",
                        verbose_name="Revocado",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="Token expiration timestamp",
                        verbose_name="Expira el",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="Client IP address when token was issued",
                        null=True,
                        verbose_name="Dirección IP",
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(
                        blank=True,
                        help_text="Client User-Agent when token was issued",
                        verbose_name="User Agent",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who owns this refresh token",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="refresh_tokens",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Token de Refresco",
                "verbose_name_plural": "Tokens de Refresco",
                "db_table": "refresh_tokens",
                "indexes": [
                    models.Index(fields=["user"], name="refresh_tok_user_id_46676d_idx"),
                    models.Index(fields=["token"], name="refresh_tok_token_e21bac_idx"),
                    models.Index(fields=["is_revoked"], name="refresh_tok_is_revo_b5c05d_idx"),
                    models.Index(fields=["expires_at"], name="refresh_tok_expires_a128d9_idx"),
                ],
            },
        ),
    ]
