# Generated by Django 5.1.6 on 2026-03-26 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_custom_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refreshtoken',
            name='user',
        ),
        migrations.RenameIndex(
            model_name='customgroup',
            new_name='custom_grou_name_7d3839_idx',
            old_name='custom_gro_name_8c5f90_idx',
        ),
        migrations.RenameIndex(
            model_name='customgroup',
            new_name='custom_grou_deleted_42c556_idx',
            old_name='custom_gro_deleted_2b06a5_idx',
        ),
        migrations.AlterField(
            model_name='permission',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Creation timestamp', verbose_name='Creado'),
        ),
        migrations.AlterField(
            model_name='role',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Creation timestamp', verbose_name='Creado'),
        ),
        migrations.DeleteModel(
            name='RefreshToken',
        ),
    ]
