[pytest]
DJANGO_SETTINGS_MODULE = aura_document_collection_service.settings.test
python_files = test/test_*.py test/integration/test_*.py
python_classes = Test*
python_functions = test_*
addopts = --reuse-db
